version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_dw_p2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom_external_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  project2_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project2_analytics_app
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ecom_external_dw
    ports:
      - "8502:8501"  # Streamlit Dashboard URL: http://localhost:8502
      - "3001:3000"  # Dagster Asset UI: http://localhost:3001
    depends_on:
      - postgres_db
    command: ["sh", "-c", "python run_pipeline.py && streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501"]
    restart: unless-stopped

volumes:
  pgdata:
